#!/bin/bash

# Aliases that I use for git

alias gc="git commit -m"
alias gs="git status"
alias ga="git add"
alias gf="git fetch"
alias gd="git diff"
alias gdc="git diff --cached"
alias gca="git commit --amend -m"


