#!/bin/bash
set -euo pipefail

python -c "
import importlib.util
import sys
spec = importlib.util.spec_from_file_location('module.name', '$1')
foo = importlib.util.module_from_spec(spec)
sys.modules['module.name'] = foo
spec.loader.exec_module(foo)
print(foo.$2)
"